version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.5.0
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns  # Persistent storage for MLflow logs
      - ./mlflow/mlartifacts:/mlflow/mlartifacts

  training:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1  # Enable BuildKit for improved caching
    container_name: model_mavericks
    depends_on:
      - mlflow  # Ensure MLflow starts first
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app  # Mount the project folder to persist dependencies
      - ./mlflow/logs:/mlflow/logs
      - ./mlflow/best_models:/mlflow/best_models
      - /root/.cache/pip:/root/.cache/pip  # Persistent pip cache to avoid re-downloading

    command: ["python", "com/model_mavericks/ML_Flow.py", "--docker"]
