version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.5.0
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlruns  # Mount mlruns folder for persistent MLflow logs

  training:
    build: .
    container_name: model-training
    depends_on:
      - mlflow  # Ensures MLflow starts first
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: ["python", "com/model_mavericks/ML_Flow.py", "--docker"]
